### ISSUE TITLE
Surface Dock / Surface Pro 4 issues

### ISSUE THREAD

**Issue by dtanzer** [MicrosoftDocs/MicrosoftCollaboratePortal#117]
When I connect my Surface Pro 4 (with type cover attached) to my surface dock, I always have two issues:

* The login screen tries to use Windows Hello, which does not work since there is no camera. It should use PIN instead.
* When logging in, windows is in "Tablet Mode". When docked, it should be in normal mode.

I found no configuration or settings so far to change this behaviour.

**Comment by ikhapova** [comment]
It would be better to report this issue to Surface suport.

**Comment by dtanzer** [comment]
OK, fair enough.
When I searched on the microsoft homepage for a place where I could report Surface bugs, this was the only place I found. So, where can I find Surface Support?

**Comment by ikhapova** [comment]
This place looks like a good starting point - https://support.microsoft.com/en-us/products/surface-devices

**Comment by dtanzer** [comment]
I didn't find any way to report a problem or give feedback there. The only option I found was "talk to the community" - Both "chat" and "call me back" are closed. Thanks for your help anyway...
