### ISSUE TITLE
C# Visual Studio, parameter evaluation time in function dynamically set

### ISSUE THREAD

**Issue by GabrielePicco** [MicrosoftDocs/MicrosoftCollaboratePortal#127]
`for (int i = 0; i < 4; i++){
            int lv = i + 1;
            GameObject btn = Instantiate(LevelButton);
            btn.GetComponent<Button>().onClick.AddListener(() => LoadLevel(lv));
 }`

`for (int i = 0; i < 4; i++){
            GameObject btn = Instantiate(LevelButton);
            btn.GetComponent<Button>().onClick.AddListener(() => LoadLevel(i + 1));
 }`

I'm using C# to develop in Unity, but I do not think it's connected to what I think is a bug.

The codes shown have unexpectedly different behaviors: in the first case the parameter of the LoadLevel function when called is correct; in the second case the parameter is always 5, it seems that if the variable passed by the parameter is not temporary it is evaluated at the end of the cycle.

**Comment by ikhapova** [comment]
It seems that issue is not related to Collaborate documentation.
