### ISSUE TITLE
Preventing from exit running code when we have an event and code cause event fire

### ISSUE THREAD

**Issue by Mansour-Bozorgmehr** [MicrosoftDocs/MicrosoftCollaboratePortal#136]
when we have an event and we are running code and code cause to fire  event, code running jump to event method, but in the ideal form only event must run without exiting running Inline code and we continuing our code without any short exit. 

For example; In Window Application Template we have a text box with TextChange Event method. TextBox Name TextBox1.

We have code below:

1     private void textBox1_TextChanged(object sender, EventArgs e)
2     {
3           ...Some Codes
4     }
5
6     private void Test()
7     {
8            ...Some Codes
9            textBox1.Text = "Some Thing";
10          ...Some Codes else
11    }

When we pass Code Line 9, C# Jump To Line 1, but must only step over Line 9 and go to Line 10 and go down there after. (I mine; passing Line 9 cause to run TextChange Event in background, but not to go code in Line 1 and it starts to go in Line 10 immediately)

My Email Address is: mansour.bozorgmehr@gmail.com

Thanks & Regards
Mansoor Bozorgmehr 2018/10/12

**Comment by ikhapova** [comment]
This issue is not related to Collaborate. Closing.
