### ISSUE TITLE
Pages in English

### ISSUE THREAD

**Issue by AlexandraHelbling** [MicrosoftDocs/MicrosoftCollaboratePortal#149]
After the last Microsoft Dynamics BC update, there are problems with the captions. a view pages are a mix between english and german.  For example the page sales order, the menu points are in English. Customer gets confused, please change this asap. Thank you. Alexandra Helbling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6f2a73-7e78-b627-7fb4-ca358bd40664
* Version Independent ID: 41ee0198-f87f-7661-b18a-ccbc14c115c2
* Content: [View, Vote and Comment on Feedback - Collaborate](https://docs.microsoft.com/en-us/collaborate/feedback-items-view)
* Content Source: [MicrosoftCollaboratePortal/feedback-items-view.md](https://github.com/MicrosoftDocs/MicrosoftCollaboratePortal/blob/master/MicrosoftCollaboratePortal/feedback-items-view.md)
* Product: **collaborate**
* GitHub Login: @ikhapova
* Microsoft Alias: **ikhapova**

**Comment by ikhapova** [comment]
Thank you for the feedback. 
This feedback channel cannot be used to report issues related  to products other then the Collaborate. Closing the issue.
