### ISSUE TITLE
Report Builder

### ISSUE THREAD

**Issue by rolandwales10** [MicrosoftDocs/MicrosoftCollaboratePortal#156]
I have started to use Report  Builder to build SSRS reports, and I want to share some observations:

1)	Data sources
I have been using Power BI successfully to create a pivot table report by choosing the Table or Matrix wizard.  This creates a nice pivot table report.  The “Choose a data source and create a query” dialog does shows the Power BI server as a data source as it should.  However, when I create a blank report, the data source drop down does not offer any data sources on the server.  I need this in order to use a shared data source on the server.  

I was able to create a free form report by creating a chart, putting a blank table on the report form, then removing the chart.  This is a pretty roundabout way of creating a free form report.

2)	Choosing a connection to a data source
The “choose a connection to a data source” dialog shows all previous data sources that were used from the server, even ones that don’t exist anymore.  There is no apparent way of removing obsolete entries from this list.

Thank you,

Roland Wales

**Comment by ikhapova** [comment]
Thank you for the feedback. 
This feedback channel cannot be used to report issues related to products other then the Collaborate. Closing the issue.
