### ISSUE TITLE
Would be interested to see on how to remove users from the account too 

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/MicrosoftCollaboratePortal#160]
We had an issue where we were not able to remove one of the user. Would love to see the documentation on how to remove the user from the account 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a45fd270-e896-7b89-4485-9dc4be0d9370
* Version Independent ID: 303ad49f-528f-797d-b4f8-4b6d608dca9d
* Content: [Troubleshooting Guide - Collaborate](https://docs.microsoft.com/en-us/collaborate/troubleshooting)
* Content Source: [MicrosoftCollaboratePortal/troubleshooting.md](https://github.com/MicrosoftDocs/MicrosoftCollaboratePortal/blob/master/MicrosoftCollaboratePortal/troubleshooting.md)
* Product: **collaborate**
* GitHub Login: @ikhapova
* Microsoft Alias: **ikhapova**

**Comment by ikhapova** [comment]
How to remove a user from Collaborate engagement is described in this article https://docs.microsoft.com/en-us/collaborate/managing-org-users#how-to-remove-a-participant. Hope it helps!
