### ISSUE TITLE
If user is not able to provide feedback to the engagement?

### ISSUE THREAD

**Issue by DeniseChien** [MicrosoftDocs/MicrosoftCollaboratePortal#68]
Could you please guide what kind of conditions user could not provide feedback associated with the engagement?

i.e., Users cannot see the engagement, after clicking “Add New” from MS Collaborate Dashboard.

Thanks for the help in advance.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 83c7b1c8-76c5-d954-f4cd-bc5d5646aaf0
* Version Independent ID: f6a22b1b-b5e0-c49d-4768-4f6a05349c58
* Content: [Working with Feedback work items - Collaborate](https://docs.microsoft.com/zh-tw/collaborate/feedback-items)
* Content Source: [MicrosoftCollaboratePortal/feedback-items.md](https://github.com/MicrosoftDocs/MicrosoftCollaboratePortal/blob/master/MicrosoftCollaboratePortal/feedback-items.md)
* Service: **unspecified**
* GitHub Login: @ikhapova
* Microsoft Alias: **ikhapova**

**Comment by ikhapova** [comment]
Hi Denise, thank you for the feedback. User will not be able to submit feedback if he/she does not belong to any engagement. Development team is looking into to how we can improve experience for this scenario.

**Comment by ikhapova** [comment]
We have also update the article to explain the behavior.
