### ISSUE TITLE
BETA Testing / Microsoft Collaborate

### ISSUE THREAD

**Issue by Olio03** [MicrosoftDocs/MicrosoftCollaboratePortal#69]
Dear Sir / Madam

I am trying to set up my Microsoft Collaborate Migration, however I am having some problems and would be appreciative if you good sort them out.

I dont see any of my programs I have participated in or wish to continue participating with, and therefore would like to know how to do this please i.e Microsoft Office, Microsoft Windows Service Pack, Microsoft SQL Server etc.

I hope you can sort this out for me please and tell me what I need to do.

Yours Faithfully

Oliver Hatton
Tel. +44 1275 373449
Email: olio03@live.com

**Comment by mimcco** [comment]
Hi Oliver,

Can you clarify the problems you are having? I’m not sure what exactly you need help sorting out.

Thanks,

-Mike

**Comment by Olio03** [comment]
Hi Mike, any update? Ive also heard there is Microsoft Office 2019 coming this year? Can I be a tester?

**Comment by mimcco** [comment]
Hi Oliver,

Programs are operated individually by the various program administrators within Microsoft. Just as it was with Connect, Collaborate is just the platform that the programs are run on. I work on the Collaborate platform and don’t have a lot of insights into the various requirements for each program. I do know this, all of the programs are by invite only so the program administrators usually contact the people/companies they want to participate. If you were part of a program on Connect that has moved to Collaborate, you should be able to contact whoever you always contacted to get more information. If the Connect program you were a part of is not on Collaborate, it means that the program has closed.

I have no idea if there is a beta testing program for Office 2019…

Sorry I can’t be much help.

Regards,

Mike McCoy

**Comment by Olio03** [comment]
Mike,

Their email address, officeconnectteam@microsoft.com doesnt work.

Oliver
________________________________

**Comment by mimcco** [comment]
Hi Oliver,

I was able to find the following links:

Read this one first: https://go.microsoft.com/fwlink/?linkid=872263
Then go to this: https://go.microsoft.com/fwlink/?linkid=872092

Thanks,

-Mike

**Comment by Olio03** [comment]
Hi Mike. I think ive got it just trying to work out where the packages are to download for the .exe

Thanks in the mean time.

Oliver
________________________________

**Comment by Olio03** [comment]
Hi Mike


Just a quick question, I am now a member of the office 2019 testing, but im having trouble activating it, do I use the volume code( it doesn't accept it) or what do I do?


Thanks


Oliver


________________________________

**Comment by Olio03** [comment]
Hi Mike


Just another thing, where / how do I access the Microsoft Office 2019 CDN.


Can you let me know please.


Oliver


________________________________

**Comment by mimcco** [comment]
I have no idea. Did they provide any way to contact them for support?

**Comment by Olio03** [comment]
Hi Mike

No luck with Microsoft.

Any ideas?

Oliver
________________________________

**Comment by ikhapova** [comment]
The issue is related to participation in early preview on Microsoft products, not about Collaborate portal itself.
