### ISSUE TITLE
New patches break RDP client

### ISSUE THREAD

**Issue by rand0m1ze** [MicrosoftDocs/MicrosoftCollaboratePortal#72]
KB4103718 and KB4103712 patches are breaking RDP client connectivity on Windows7x64. I believe it's something to do with NLP, not sure if this is the right place to report this but these patches are new and causing problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c7b1c8-76c5-d954-f4cd-bc5d5646aaf0
* Version Independent ID: f6a22b1b-b5e0-c49d-4768-4f6a05349c58
* Content: [Working with Feedback work items - Collaborate](https://docs.microsoft.com/en-us/collaborate/feedback-items#how-to-create-and-save-queries-for-feedback-work-items)
* Content Source: [MicrosoftCollaboratePortal/feedback-items.md](https://github.com/MicrosoftDocs/MicrosoftCollaboratePortal/blob/master/MicrosoftCollaboratePortal/feedback-items.md)
* Service: **windows**
* GitHub Login: @ikhapova
* Microsoft Alias: **ikhapova**

**Comment by rand0m1ze** [comment]
"An authentication error has occured. The function requested is not supported.
Remote computer etcetcetc "

**Comment by ikhapova** [comment]
Thank you for sharing feedback. This is very unfortunate that new patches caused regression.
You could request assistance at https://support.microsoft.com/en-us/contactus/
