### ISSUE TITLE
Microsoft power point - 2016 issue with Undo 

### ISSUE THREAD

**Issue by Archana-g-s** [MicrosoftDocs/MicrosoftCollaboratePortal#77]
Hey Team, 

Consider there is a 5 row x 4 column table created in power point (2016).  
Merge last two columns in rows 2 and 4. 
Now, try to change width of last column - Then undo (Ctrl + z). 
In the first instance or second instance (of column width change and undo), the powerpoint becomes unresponsive.

Thanks to recovery feature, the work done is not lost.. But I thought i will let you know. 

Cheers,
Archana

**Comment by ikhapova** [comment]
Thank you for the feedback.
It is best to report it through Office feedback channel, so that Office team can address it.
