### ISSUE TITLE
What's the difference between "feedback" and Professional Support 

### ISSUE THREAD

**Issue by Weishunjuan** [MicrosoftDocs/MicrosoftCollaboratePortal#82]
I'd like to know which solution is the best for my company while handling bugs with our x86 server products in hardware cert tests. How does feedback work and how does differ from professional support (https://support.microsoft.com/en-us/gp/offerprophone?wa=wsignin1.0)?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c7b1c8-76c5-d954-f4cd-bc5d5646aaf0
* Version Independent ID: f6a22b1b-b5e0-c49d-4768-4f6a05349c58
* Content: [Working with Feedback work items - Collaborate](https://docs.microsoft.com/en-us/collaborate/feedback-items)
* Content Source: [MicrosoftCollaboratePortal/feedback-items.md](https://github.com/MicrosoftDocs/MicrosoftCollaboratePortal/blob/master/MicrosoftCollaboratePortal/feedback-items.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @ikhapova
* Microsoft Alias: **ikhapova**

**Comment by StingyJack** [comment]
"Feedback" carries **no guarantee of acknowledgement, response, or resolution**, despite its clear outward appearance as a customer support tool. Only issues with the most votes get looked at, not the issues that are the most impactful to the user base. If you need real help, do not count on "feedback".

By several accounts from people I've worked with over the years, Professional Support is a proper support apparatus that gets resolutions to issues. (I've not dealt with PS personally.)
