### ISSUE TITLE
Windows Server 2019

### ISSUE THREAD

**Issue by Olio03** [MicrosoftDocs/MicrosoftCollaboratePortal#94]
Hi

I've found a bug in Windows Server 2019 Standard, the user account database crashes when loading it in the control panel through the local administrator account.

Let me know if you need more information.

O. Hatton

**Comment by ikhapova** [comment]
Thank you for the feedbcak. It is best to report this issue to customer support.
Closing as feeback is not related to Collaborate.

**Comment by emreyilmaz1907** [comment]
Exchange Server Unified messaging show in server tab .
