### ISSUE TITLE
shows email id exists and prompts invalid mail id when try to login

### ISSUE THREAD

**Issue by SanthoshReddyV** [MicrosoftDocs/MicrosoftCollaboratePortal#98]
![microsoft sign in](https://user-images.githubusercontent.com/40892936/42381718-82caa5a8-8121-11e8-929a-38fb403106f0.png)

**Comment by ikhapova** [comment]
It is very unpleasant experience.n
If you still experince the issue, please reach out to support as decsribed [here](https://docs.microsoft.com/en-us/collaborate/support#how-to-get-support)
